project:
  type: website
lang: de 

website:
  title: "Python Startup For Engineers"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lg-eng/PythonStartupForEngineers
  cookie-consent:
    type: express
    style: headline
    palette: dark
    tracking: true
  google-analytics:
    tracking-id: "G-4T0K9QTW06"
    anonymize-ip: true

format:
  html:
    theme: cosmo
    css: styles.css





